spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/nexora_store?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME:nexora_app}
spring.datasource.password=${DB_PASSWORD:NexoraDev123}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=false
app.mail.enabled=false
app.mail.from=no-reply@nexora.local
